config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :trips do
    resources :itineraries
  end

  resources :budgets

  root to: 'trips#index'

end

app/models/budget.rb
class Budget < ActiveRecord::Base

	belongs_to :user	

	validates :budget, presence: true
	validates :date_from, presence: true
	validates :date_to, presence: true
	validate :time_uniqueness, on: :create
	validates :user_id, presence: true

	include CalculateBudget

	class << self
  	def for_year(user, date=Time.zone.now)
    	self.where("date_from >= ? and date_from <= ? and user_id = ?", date.beginning_of_year, date.end_of_year, user)
  	end

  	def yearly_budget(user, date=Time.zone.now)
    	self.for_year(user, date).map(&:budget).reduce(:+) || 0.00
  	end

  	def remaining_yearly_budget(user)
    	self.yearly_budget(user)-Itinerary.total_yearly_estimated_cost(user)
  	end
	end

	private

	def time_uniqueness
  	if Budget.where(['(date_from <= ? OR date_to >= ?) AND user_id = ?', date_from, date_to, self.user.id]).size > 0
    	errors[:base] << "Please choose different dates. It seems like you have already set a budget for those dates."
  	end
  end

end

app/models/concerns/calculate_budget.rb
module CalculateBudget

	extend ActiveSupport::Concern

	module ClassMethods

		def for_year(date=Time.zone.now)
			self.where("date_from > ? and date_from < ?", date.beginning_of_year, date.end_of_year)
		end

		def yearly_budget(date=Time.zone.now)
    	self.for_year(date).map(&:budget).reduce(:+) || 0.00
  	end

  	def remaining_yearly_budget
    	self.yearly_budget-Itinerary.total_yearly_estimated_cost
  	end

	end

end

app/models/concerns/calculate_estimated_cost.rb
module CalculateEstimatedCost

	extend ActiveSupport::Concern

	module ClassMethods

		def for_user(user)
      self.where(user_id: user)
    end

		def for_year(date=Time.zone.now)
			self.where("travel_on > ? and travel_on < ?", date.beginning_of_year, date.end_of_year)
		end

		def total_yearly_estimated_cost(date=Time.zone.now)
			self.for_year(date).map(&:estimated_cost).reduce(:+) || 0.00
		end

	end

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
	belongs_to :trip
	belongs_to :user

	validates :user_id, presence: true
	validates :location, presence: true
	
	include CalculateEstimatedCost

	class << self
    def for_user(user)
      self.where(user_id: user)
    end

    def for_year(date=Time.zone.now)
      self.where("itineraries.travel_on > ? and travel_on < ?", date.beginning_of_year, date.end_of_year)
    end

    def total_yearly_estimated_cost(user, date=Time.zone.now)
      self.for_user(user).for_year(date).map(&:estimated_cost).reduce(:+) || 0.00
    end
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true
	has_many :itineraries

	class << self
  	def ordered_by_name(user)
    	self.where(user_id: user.id).order(:name)
  	end
	end

	def to_s
		name
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :budgets
	has_many :trips
	has_many :itineraries

	def name
  	[first_name, last_name].join(" ")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

before_action :find_budget, only: [:update, :destroy]

def create
	@budget = Budget.new(budget_params)
	@budget.attributes = params[:budget].permit(:budget, :date_from, :date_to)
  @budget.user_id = current_user.id
	if @budget.save
		flash[:notice] = "Successfully added your budget"	
	else
		flash[:alert] = @budget.errors.full_messages.join("<br />")
	end
	redirect_to trips_path
end

def update
	@budget.attributes = params[:budget].permit(:budget, :date_from, :date_to)
  @budget.user_id = current_user.id
	if @budget.update(budget_params)
		flash[:notice] = "Successfully added your budget"
	else
		flash[:alert] = @budget.errors.full_messages.join("<br />")
	end
	redirect_to trips_path
end

def destroy
	@budget.destroy
	flash[:notice] = "Successfully deleted your budget"
	redirect_to trips_path
end

private

	def budget_params
		params.require(:budget).permit(:budget, :date_from, :date_to)
	end

	def find_budget
		@budget = Budget.find(params[:id])
	end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

helper_method :sort_column, :sort_direction
before_action :find_trip, only: [:index, :show, :new, :edit]

def show
  @itinerary = Itinerary.find(params[:id])
end

def index
	@itineraries = @trip.itineraries.order(sort_column + " " + sort_direction)
end

def new
	@itinerary = Itinerary.new(trip: @trip)
end

def update
	@itinerary = Itinerary.find(params[:id])
	@itinerary.user_id = current_user.id
	if @itinerary.update(itinerary_params)
		redirect_to action: 'show', id: @itinerary.id
	else
		render action: 'edit'
	end
end

def edit
	@itinerary = Itinerary.find(params[:id])
end

def create
	@itinerary = Itinerary.new(itinerary_params)
	@itinerary.user_id = current_user.id
  if @itinerary.save
    redirect_to action: 'show', id: @itinerary.id
  else
    render action: 'new'
  end
end

def destroy
	@itinerary = Itinerary.find(params[:id])
	@itinerary.destroy
	flash[:notice] = "You have successfully deleted itinerary"
	redirect_to action: 'index'
end

private
	
	def itinerary_params
		params.require(:itinerary).permit(:location, :travel_on, :estimated_cost, :trip_id)
	end

	def sort_column
  	Itinerary.column_names.include?(params[:sort]) ? params[:sort] : "location"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def find_trip
  	@trip = Trip.find(params[:trip_id])
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

helper_method :sort_column, :sort_direction
before_action :find_trip, except: [:index, :new, :create]

before_action :list_budget, only: [:index]


def show
end

def index
	@trips = Trip.where(user_id: current_user.id).order([sort_column, sort_direction].join(" "))
end

def new
	@trip = Trip.new
end

def update
	@trip.attributes = params[:trip].permit(:name)
 	@trip.user_id = current_user.id
	if @trip.update(trips_params)
		redirect_to action: 'show', id: @trip.id
	else
		render action: 'edit'
	end
end

def edit
end

def create
	@trip = Trip.new(trips_params)
	@trip.attributes = params[:trip].permit(:name)
  @trip.user_id = current_user.id
  if @trip.save
    redirect_to action: 'show', id: @trip.id
  else
    render action: 'new'
  end
end

def destroy
	@trip.destroy
	flash[:notice] = "You have successfully deleted trip"
	redirect_to action: 'index'
end

private

	def list_budget
		@budgets = Budget.where(user_id: current_user.id).order('date_from desc')
		@budget = Budget.new
	end
	
	def find_trip
		id = params[:trip_id] ? params[:trip_id] : params[:id]
   	@trip = Trip.find(id)
	end

	def trips_params
		params.require(:trip).permit(:name)
	end

	def sort_column
  	Trip.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)
  	title ||= column.titleize
  	css_class = "current "+sort_direction if column == sort_column
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  	link_to title, {sort: column, direction: direction}, {class: css_class}
	end

	def itinerary_row_class(itinerary)
    'danger' if  Itinerary.total_yearly_estimated_cost(current_user.id) > Budget.yearly_budget(current_user.id)
  end

  def show_remaining_budget
    yearly_budget_remaining = number_to_currency(Budget.remaining_yearly_budget(current_user.id), unit: "PHP")
    content_tag :h2, "Remaining Yearly Budget: "+ yearly_budget_remaining
  end

end

app/views/budgets/_form.html.erb
<% @budget = budget %>
<%= form_for(@budget, html: {role: 'form'}) do |f| %>
	<div class="form-group">
		<%= f.label :budget, class: "control-label" %>
		<%= f.text_field :budget, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :date_from, class: "control-label" %>
		<%= f.date_select :date_from, class: "form-control" %>
	</div>
	<div>
		<%= f.label :date_to, class: "control-label" %>
		<%= f.date_select :date_to, class: "form-control" %>
	</div>

	<div class="form-group">
    <%= f.submit name, class: "btn btn-small btn-primary" %>

    <% if @budget.try(:id) %>
      <%= link_to 'Delete', budget_path(@budget.id), method: 'delete', confirm: "Are you sure you want to delete this?", class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/budgets/_list.html.erb
<section class="budget">
  <h1><a href="#" class="title">Set your budget</a></h1>
  <section class="budgets" style="display: none;">
    <%= render partial: 'budgets/form', locals: { budget: @budget, name: "Create" } %>
    <% @budgets.each do |budget| %>
      <%= render partial: 'budgets/form', locals: { budget: budget, name: 'Update' } %>
    <% end %>
  </section>
</section>

app/views/itineraries/_form.html.erb
<ul>
  <% @itinerary.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for([@trip, @itinerary], html: { role: 'form' }) do |f| %>
  
  <div class="form-group">
    <%= f.label :trip_id, class: 'control-label' %>
    <%= f.collection_select :trip_id, Trip.ordered_by_name(current_user), :id, :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location, class: 'control-label' %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :travel_on, class: 'control-label' %>
    <%= f.date_field :travel_on, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :estimated_cost, class: 'control-label' %>
    <%= f.text_field :estimated_cost, class: 'form-control', value: (number_with_precision(f.object.estimated_cost, precision: 2) || 0) %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/itineraries/edit.html.erb
<h1>Edit Itinerary</h1>
<%= render 'form' %>

app/views/itineraries/index.html.erb
<h1>Itineraries</h1>
<table>
  <tr>
    <th><%= sortable 'location' %></th>
    <th><%= sortable 'travel_on', 'Travel Date' %></th>
    <th><%= sortable 'estimated_cost' %></th>
    <th><%= sortable 'trip_id' %></th>
    <th></th>
  </tr>
<% @itineraries.each do |itinerary| %>
  <tr class="<%= itinerary_row_class(itinerary) %>">
    <td><%= itinerary.location %></td>
    <td><%= itinerary.travel_on %></td>
    <td><%= number_to_currency(itinerary.estimated_cost, unit: "PHP") %></td>
    <td><%= itinerary.trip %></td>
    <td>
    	<%= link_to 'Show', trip_itinerary_path(itinerary.trip, itinerary.id), class: 'btn btn-default' %>
  		<%= link_to 'Edit', edit_trip_itinerary_path(@trip.id, itinerary.id), class: 'btn btn-default' %>
      <%= link_to 'Delete', trip_itinerary_path(@trip.id, itinerary.id), method: :delete, class: 'btn btn-default' %>
  	</td>	
  <tr>
<% end %>

</table>

<%= link_to "New", { action: 'new' } , class: 'btn btn-default' %>

<%= show_remaining_budget %>

app/views/itineraries/new.html.erb
<h1>New Itinerary</h1>
<%= render 'form' %>

app/views/itineraries/show.html.erb
<h1>Itinerary <%= @itinerary.id %></h1>
<ul class="list-unstyled">
	<li>Trip: <%= @itinerary.trip %></li>
  <li>Location: <%= @itinerary.location %></li>
  <li>Travel Date: <%= @itinerary.travel_on %></li>
  <li>Estimated Cost: <%= number_to_currency(@itinerary.estimated_cost, unit: "PHP") %></li>
</ul>
<%= form_for([@itinerary.trip, @itinerary], method: :delete, html: {role: 'form'}) do |f| %>
	<%= f.submit 'Delete Itinerary', class: 'btn btn-primary' %>
	<%= link_to 'Back', trip_itineraries_path(@itinerary.trip) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li class="active"><%= link_to "Home", trips_path %></li>
  </ul>


  <% if current_user %>
    <ul class="nav navbar-nav pull-right">
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Hello, <%= current_user.name %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
      </li>
    </ul>
  <% end %>
</div>

<%= render 'shared/flash_message' %>
<%= yield %>

</body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg %>
  </div>
<% end %>

app/views/trips/_form.html.erb
<ul>
  <% @trip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_for(@trip, html: { role: 'form' }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>
<%= render 'form' %>

app/views/trips/index.html.erb
<h1>Plan Your Trips</h1>

<%= render 'budgets/list' %>

<%= show_remaining_budget %>

<table>
  <tr>
    <th><%= sortable 'name' %></th>
    <th></th>
  </tr>
<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.name %></td>
    <td>
    	<%= link_to 'Show', trip_path(trip.id), class: 'btn btn-default' %>
  		<%= link_to 'Edit', edit_trip_path(trip.id), class: 'btn btn-default' %>
      <%= link_to 'Delete', trip_path(trip.id), method: :delete, class: 'btn btn-default' %>
  	</td>	
  <tr>
<% end %>

</table>

<%= link_to "New", { action: 'new' } , class: 'btn btn-default' %>

<h2>Remaining budget: <em><%= number_to_currency(@remaining_budget, unit: "PHP") %></em></h2>

app/views/trips/new.html.erb
<h1>New Trip</h1>
<%= render 'form' %>

app/views/trips/show.html.erb
<h1>Trip <%= @trip.id %></h1>
<ul class="list-unstyled">
  <li>Name: <%= @trip.name %></li>
</ul>
<%= link_to 'View Itineraries', trip_itineraries_path(@trip.id), class: 'btn btn-primary' %>
<%= form_for(@trip, method: :delete, html: {role: 'form'}) do |f| %>
	<%= f.submit 'Delete Trip', class: 'btn btn-primary' %>
	<%= link_to 'Back', action: 'index' %>
<% end %>